# Inserts a blank line between shell prompts
add_newline = true

[username]
show_always = true
disabled = false
style_root = "bold red"
style_user = "bold yellow"
format = "[$user](bold green)[@](bold green)"


[hostname]
disabled = false
ssh_only = false
format = "[$hostname](bold green) in "
#prefix = "@"
#suffix = ">>"

[directory]
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "../"
#prefix = " ğŸ“‚ï¸ "

[battery]
disabled = false
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 30
style = "bold red"


